meta_product_name: "ActiVities"
meta_title: "ActiVities- Find new buddies near you"
meta_description: "With ActiVities you can partake in events created by people around your city, meet new people and make friends through practicing !"
meta_image: "activities-og.png"
